<a href="https://colab.research.google.com/github/Anjasfedo/data-analysis/blob/main/NumPy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Introduction
What is NumPy?

NumPy is multi-dimensional array library (1D, 2D, 3D, etc)

How are list different from NumPy?
1. list:
  - slow (list contain 4 space such Size, Reference Count, Object Type, Object Value)
2. NumPy:
  - Fast (because of fixed type, by default got Int32)
  - faster to read less bytes of memory
  - no type checking when iterating through objects
  - Contiguous Memory
  - use SIMD (single instruction multiple data) Vector Processing
  - Effective Cache utilization

How are lists different from NumPy?
1. list, we can do some method:
  - insertion
  - deletion
  - appending
  - concatenation
  - etc
2. NumPy:
  - insertion
  - deletion
  - appending
  - concatenation
  - etc
  - Moree....

Application of NumPy?
- Mathematics (MATLAB Replacement)
- Plotting (Matplotlib)
- Backend (Pandas, Connect 4, Digital Photography)
- Machine Learning


# Import NumPy

In [1]:
import numpy as np
import sys

# The Basics

In [18]:
a = np.array([1, 2, 3], dtype="int16")
print(a)

[1 2 3]


In [11]:
b = np.array([[9.0, 8.0, 7.0], [6.0, 5.0, 4.0]])
print(b)

[[9. 8. 7.]
 [6. 5. 4.]]


In [12]:
# Get dimension
print(a.ndim)
print(b.ndim)

1
2


In [13]:
# Get shape
print(a.shape)
print(b.shape) # (row, column)

(3,)
(2, 3)


In [14]:
# Get type
print(a.dtype)
print(b.dtype)

int16
float64


In [19]:
# Get size (on memory)
print(a.itemsize) # int16 = 2 bytes
print(b.itemsize) # float64 = 8 bytes

2
8


In [21]:
# Get total size
print(a.size * a.itemsize)
print(b.size * b.itemsize)

# or with .nbytes
print(a.nbytes)
print(b.nbytes)

6
48
6
48


# Accessing/Changing spesific elements, rows, columns, etc

## 2D example

In [32]:
a = np.array([[1, 2, 3, 4, 5, 6, 7], [8, 9, 10, 11, 12, 13, 14]])
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [24]:
# Get specific element [row, column] by indexing (on lists use [row][column])
a[1, 5]

13

In [27]:
# Get specific row
a[0, :]

array([1, 2, 3, 4, 5, 6, 7])

In [28]:
# Get specific column
a[:, 2]

array([ 3, 10])

In [29]:
# Getting little more fancy [start index:end index:step size]
a[0, 1:6:2]

array([2, 4, 6])

In [33]:
# Change specific element
print(a[1, 5])

a[1,5] = 20

print(a[1, 5])

13
20


In [35]:
# Change entire column
print(a)

# a[:, 2] = 5
a[:, 2] = [1, 2]

print(a)

[[ 1  2  5  4  5  6  7]
 [ 8  9  5 11 12 20 14]]
[[ 1  2  1  4  5  6  7]
 [ 8  9  2 11 12 20 14]]


## 3D example

In [39]:
b = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
print(b)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [40]:
# Get specific element (work outside in)
b[0, 1, 1]

4

In [41]:
# Change
print(b)
print(b[:, 1, :])

b[:, 1, :] = [[999, 999], [999, 999]]

print(b)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
[[3 4]
 [7 8]]
[[[  1   2]
  [999 999]]

 [[  5   6]
  [999 999]]]


# Initialixing Different Types of Arrays

In [42]:
# All 0s matrix
np.zeros((2, 3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [43]:
# All 1s matrix
np.ones((4, 2, 2), dtype="int32")

array([[[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]]], dtype=int32)

In [47]:
# Any other number
print(np.full((2, 2), 99))

print(np.full(b.shape, 99))

[[99 99]
 [99 99]]
[[[99 99]
  [99 99]]

 [[99 99]
  [99 99]]]


In [46]:
# Any ohter number (full_like)
c = np.full_like(a, 4)

print(a.shape)
print(c.shape)

(2, 7)
(2, 7)


In [49]:
# Random decinal numbers
print(np.random.rand(4, 2))

# With shape of other array
print(np.random.random_sample(a.shape))

[[0.33535754 0.27246718]
 [0.19285817 0.75159163]
 [0.35598828 0.43954943]
 [0.02911239 0.81981667]]
[[0.92378486 0.43181207 0.79723274 0.04922961 0.34102799 0.62462622
  0.99582939]
 [0.10024347 0.34630488 0.34434077 0.08310565 0.08829457 0.16696367
  0.12356994]]


In [51]:
# Random integer values
print(np.random.randint(7, size=(3, 3))) # 7 is exclusive

print(np.random.randint(-2, 7, size=(3, 3)))

[[4 0 6]
 [1 1 6]
 [6 3 6]]
[[ 4 -2  5]
 [ 2 -1  5]
 [ 3  3  1]]


In [53]:
# The identity matrix
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [58]:
# Repeat an array
arr = np.array([[1, 2, 3]])

r1 = np.repeat(arr, 3, axis=0)
print(r1)

[[1 2 3]
 [1 2 3]
 [1 2 3]]
